include $(GOROOT)/src/Make.inc

TARG=ircclient
GOFILES=\
	basicprotocol.go		\
	ircclient.go			\
	ircconn.go			\
	ircmsg.go			\
	plugin.go			\
	stack.go			\
	conf.go				\
	auth.go				\
	throttle-ircu.go
include $(GOROOT)/src/Make.pkg
